#!/usr/bin/env python3
"""Normalize every structured result in the repo into results/summary/ (continuous-bench
condition 2: machine-readable accumulation, kept separate from the raw logs).

Inputs (read-only):
  results/quality/*.json                 six historical schema variants (see gap audit)
  results/raw/**/app-path*/*.json        device per-run records (BenchmarkResult shape)

Outputs (overwritten each run — derived data, raw stays canonical):
  results/summary/quality.csv
  results/summary/device-runs.csv
  results/summary/README.md

Stdlib only. Idempotent. New writers should emit schema/result.v1.json natively;
this script is the bridge for pre-v1 records.
"""
import csv, glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "results", "summary")
os.makedirs(OUT, exist_ok=True)


def rel(p):
    return os.path.relpath(p, ROOT)


def build_quality():
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "results", "quality", "*.json"))):
        d = json.load(open(f))
        if "mode" in d and "results" in d:  # fakequant harness variant
            rows.append({
                "source": rel(f), "tag": d.get("mode"), "n": d.get("n"),
                "correct": d.get("ok"),
                "acc": round(d.get("ok", 0) / d["n"], 4) if d.get("n") else None,
                "max_tokens": None, "runtime_build": None, "backend": None,
                "bundle": None, "has_correction_note": "rescored" in d,
                "gen_tokens_median": None, "decode_tps_median": None,
            })
            continue
        rows.append({
            "source": rel(f), "tag": d.get("tag"), "n": d.get("n"),
            "correct": d.get("correct"), "acc": d.get("acc"),
            "max_tokens": d.get("max_tokens") or d.get("max_output_tokens"),
            "runtime_build": d.get("runtime_build"), "backend": d.get("backend"),
            "bundle": d.get("bundle"),
            "has_correction_note": bool(d.get("correction") or d.get("note")),
            "gen_tokens_median": d.get("gen_tokens_median"),
            "decode_tps_median": d.get("decode_tps_median"),
        })
    path = os.path.join(OUT, "quality.csv")
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)
    return path, len(rows)


def build_device():
    rows = []
    for f in sorted(glob.glob(os.path.join(ROOT, "results", "raw", "**", "app-path*", "*.json"),
                              recursive=True)):
        try:
            d = json.load(open(f))
        except Exception:
            continue
        m, dev, model = d.get("metrics", {}), d.get("device", {}), d.get("model", {})
        if not m:
            continue
        rows.append({
            "source": rel(f),
            "campaign": rel(os.path.dirname(os.path.dirname(f))),
            "timestamp": d.get("timestamp"),
            "runtime": d.get("runtime"),
            "engine_version": d.get("engineVersion"),
            "engine_artifact": d.get("engineArtifact"),
            "model_id": model.get("id"),
            "quantization": model.get("quantization"),
            "task": d.get("task"),
            "harness_stamp": m.get("harnessStamp"),
            "decode_tps": m.get("decodeTokensPerSecond"),
            "decode_tps_wall": m.get("decodeTokensPerSecondWallClock"),
            "prefill_tps": m.get("promptTokensPerSecond"),
            "prompt_tokens": m.get("promptTokenCount"),
            "gen_tokens": m.get("generatedTokenCount"),
            "ttft_ms": m.get("firstTokenLatencyMS"),
            "mem_footprint_median_mb": m.get("memoryMedianMB"),
            "mem_resident_median_mb": m.get("memoryMedianResidentMB"),
            "energy_j_per_tok": m.get("energyJoulesPerToken"),
            "thermal_initial": m.get("initialThermalState"),
            "thermal_final": m.get("finalThermalState"),
            "battery_state": dev.get("batteryState"),
            "cold_run": m.get("coldRun"),
            "device": dev.get("modelIdentifier"),
            "os_version": dev.get("systemVersion"),
        })
    rows.sort(key=lambda r: (r["campaign"], r["timestamp"] or ""))
    path = os.path.join(OUT, "device-runs.csv")
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader(); w.writerows(rows)
    return path, len(rows)


def main():
    qp, qn = build_quality()
    dp, dn = build_device()
    readme = os.path.join(OUT, "README.md")
    with open(readme, "w") as fh:
        fh.write(
            "# results/summary — derived, machine-readable accumulation\n\n"
            "Generated by `scripts/build_summary.py` from `results/quality/` and the\n"
            "committed `app-path*/` device records. Raw logs stay canonical; this layer is\n"
            "for querying, regression tracking, and leaderboard export — regenerate any\n"
            f"time with `python3 scripts/build_summary.py`.\n\n"
            f"- `quality.csv` — {qn} GSM8K report rows (all historical schema variants normalized)\n"
            f"- `device-runs.csv` — {dn} per-run device records (speed / memory / energy cells)\n\n"
            "Engine version is absent from pre-v1 rows (see the gap audit). Builds from\n"
            "2026-08-05 onward stamp `engineVersion`/`engineArtifact` into every device row\n"
            "(`stamp_engine_pins.sh` -> Info.plist -> BenchmarkResult), surfaced here as\n"
            "`engine_version`/`engine_artifact`; new writers must emit `schema/result.v1.json`.\n"
        )
    print(f"wrote {qp} ({qn} rows)")
    print(f"wrote {dp} ({dn} rows)")
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
